---
- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: present

- name: Install Docker Engine
  apt:
    name: "{{ docker_package }}"
    state: present
    update_cache: yes

- name: Ensure Docker is started and enabled
  service:
    name: docker
    state: started
    enabled: yes
    
- name: Add ansible_user to the docker group
  user:
    name: "{{ ansible_user }}"
    group: docker
    append: yes
  become: true

