---
- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    mode: 'u+x'

- name: Verify Docker Compose installation
  command: docker compose version
  register: docker_compose_installed_version
  changed_when: false

- name: Print Docker Compose version
  debug:
    msg: "{{ docker_compose_installed_version.stdout }}"
